---
title: "County Level Averages"
output: html_notebook
---

TO DO
1. Get California county->grid join, join that to PM2.5 data
2. Group by county, compare to George's numbers
3. Compare our numbers to Childs' population-weighted numbers?
4. Try attempt at small multiples maps of California for each year to export as PNG for George to play with in Illustrator 

```{r}
library(tidyverse)
library(here)
library(janitor)
library(sf)
library(lubridate)
library(rio)
library(waldo)
```

```{r}
ca_county_grids <- read_csv("ca_county_grid.csv")
levine_results <- read_csv(here("levine_county_level_results", "county_yearly_averages.csv"))
```

```{r}
alameda <- ca_county_grids %>% 
  filter(county == "Alameda") %>% 
  filter(date >= "2018-01-01", date <= "2018-12-31")
```

```{r}
smoke_days_by_year <- ca_county_grids %>% 
  group_by(county, year = floor_date(date, "year")) %>% 
  summarize(days = n_distinct(date)) %>% 
  mutate(year = as.numeric(format(year,'%Y'))) %>% 
  select(county, year, days) %>% 
  pivot_wider(names_from = year, values_from = days)

smoke_pm25_by_year <- ca_county_grids %>% 
  group_by(county, date = floor_date(date, "year")) %>% 
  summarize(pm25 = round(mean(pm25), digits = 2)) %>% 
  mutate(year = as.numeric(format(date,'%Y'))) %>% 
  select(county, year, pm25) %>% 
  pivot_wider(names_from = year, values_from = pm25)
```
```{r}
summary(levine_results)
```

```{r}
summary(smoke_pm25_by_year)
```

```{r}
average_intensity_of_smoke_day <-
  pm25_by_year %>% 
  inner_join(smoke_days_by_year, by = c("county", "year")) %>% 
  mutate(intensity = pm25/days)
  

```


